apiVersion: v2
name: primary-site
description: Foxglove Primary Site
icon: https://foxglove.dev/images/logo-icon-round.png

type: application

version: "0.0.59"

appVersion: "1b4d4155a4c1efbc12450e870d32229815710078"
