apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-controller
spec:
  selector:
    matchLabels:
      app: foxglove-edge-site
  template:
    metadata:
      labels:
        app: foxglove-edge-site
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: edge-controller-pv-claim
      containers:
        - name: edge-controller
          image: us-central1-docker.pkg.dev/foxglove-images/images/edge-controller:8fef61e167e6a914e5a70fba70a0fc6ec4d0ce14
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: "/var/data"
              name: pv-storage
          env:
            - name: SITE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: foxglove-site
                  key: token
                  optional: false
            - name: DATABASE_CONNECTION_STRING
              value: sqlite://file:./controller.db
            - name: STORAGE_ROOT
              value: /var/data
            - name: FOXGLOVE_API_URL
              value: "{{ .Values.globals.foxglove_api_url }}"
