apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: site-controller
spec:
  selector:
    matchLabels:
      app: foxglove-edge-site
  serviceName: "edge-controller"
  replicas: 1
  template:
    metadata:
      labels:
        app: foxglove-edge-site
    spec:
      volumes:
        - name: storage-root
          persistentVolumeClaim:
            claimName: "{{ .Values.edge_controller.storageClaim }}"
      containers:
        - name: edge-controller
          image: us-central1-docker.pkg.dev/foxglove-images/images/edge-controller:8fef61e167e6a914e5a70fba70a0fc6ec4d0ce14
          volumeMounts:
            - mountPath: "/data/edge_storage_root"
              name: storage-root
          env:
            - name: SITE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: foxglove-site
                  key: token
                  optional: false
            - name: DATABASE_CONNECTION_STRING
              value: sqlite://file:/data/edge_storage_root/foxglove.db
            - name: STORAGE_ROOT
              value: /data/edge_storage_root
            - name: FOXGLOVE_API_URL
              value: "{{ .Values.globals.foxglove_api_url }}"
